# Generated by Django 5.2.4 on 2025-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
